#!/usr/bin/env bash
# Script that installs Nginx and configure it
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R ubuntu:ubuntu /var/www
sudo echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
