#!/usr/bin/env bash
# Configuring my Nginx server so that /redirect_me to a utube page

sudo apt update -y && sudo apt upgrade -y
sudo apt install nginx -y

echo "Holberton School" >/var/www/html/index.nginx-debian.html
# Redirection
sudo sed -i '/listen \[::\]:80 default_server;/a\        rewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# 404 Page not Found
echo "Ceci n'est pas une page" >/var/www/html/404.html
sed -i '/TGUlwu4 permanent;$/a\        error_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx restart