#!/usr/bin/env bash
# display "Holberton School" 1à times using while except 9th should be "Hi"
x=1
while [ $x -le 10 ]
do
	if [ $x -eq 9 ]
	then
		echo "Holberton School"
		echo "Hi"
	else
		echo "Holberton School"
	fi
  x=$((x + 1))
done